#!/bin/bash
# Build a modern .deb for nekoray.
#
# Standards applied (Ubuntu 24.04 / Debian 12 generation):
#   * desktop entry + hicolor icon + /usr/bin launcher ship as package
#     payload (dpkg owns them: upgrade/remove/purge just work) instead of
#     being generated by postinst scripts (which never get cleaned up and
#     broke on every postinst change - upstream issues #629 / #640)
#   * Icon=nekoray resolves through the hicolor icon theme, no absolute
#     /opt path (absolute paths are what lose the icon on GNOME 46 /
#     Ubuntu 24.04); StartupWMClass matches the real WM_CLASS
#   * maintainer scripts: #!/bin/sh + set -e, guarded best-effort calls
#   * control: Section / Priority / Homepage / Installed-Depends style
#     fields, Recommends: hicolor-icon-theme, libcap2-bin for setcap
#   * dpkg-deb --root-owner-group => root:root archive owners (no sudo,
#     no uid-1001 files like upstream #1534 "No permission to write
#     /opt/nekoray") and -Zzstd compression (Debian 12+/Ubuntu 24)
#   * output name follows Debian Policy: nekoray_<version>_<arch>.deb
set -euo pipefail

version="$1"
arch="amd64"
deb_name="nekoray_${version}_${arch}"

rm -rf nekoray "$deb_name.deb" nekoray.deb

mkdir -p nekoray/DEBIAN
mkdir -p nekoray/opt
cp -r linux64 nekoray/opt/
mv nekoray/opt/linux64 nekoray/opt/nekoray
rm -rf nekoray/opt/nekoray/usr
rm -f nekoray/opt/nekoray/launcher

#### payload: desktop entry, themed icon, CLI launcher ####

mkdir -p nekoray/usr/share/applications
mkdir -p nekoray/usr/share/icons/hicolor/256x256/apps
mkdir -p nekoray/usr/share/pixmaps
mkdir -p nekoray/usr/bin

cp nekoray/opt/nekoray/nekobox.png nekoray/usr/share/icons/hicolor/256x256/apps/nekoray.png
# alias kept so anything still asking for the old "nekobox" icon name works
cp nekoray/opt/nekoray/nekobox.png nekoray/usr/share/icons/hicolor/256x256/apps/nekobox.png
cp nekoray/opt/nekoray/nekobox.png nekoray/usr/share/pixmaps/nekoray.png

cat >nekoray/usr/share/applications/nekoray.desktop <<-EOF
[Desktop Entry]
Type=Application
Version=1.0
Name=nekoray
GenericName=Proxy Client
Comment=Qt based cross-platform GUI proxy configuration manager (backend: sing-box)
TryExec=nekoray
Exec=nekoray
Icon=nekoray
Terminal=false
StartupNotify=false
StartupWMClass=nekoray
Categories=Network;
Keywords=proxy;v2ray;sing-box;xhttp;vless;trojan;vmess;clash;
EOF

cat >nekoray/usr/bin/nekoray <<-EOF
#!/bin/sh
# nekoray launcher (deb): keep /opt/nekoray root-owned and never writable
# required; user data lives in ~/.config/nekoray (-appdata is appended so
# any arguments the user passes, including "-appdata /path", still win).
export PATH="/opt/nekoray:\$PATH"
exec /opt/nekoray/nekobox "\$@" -appdata
EOF
chmod 0755 nekoray/usr/bin/nekoray

# Debian Policy 12.5: copyright + changelog in /usr/share/doc/<package>
mkdir -p nekoray/usr/share/doc/nekoray
cat >nekoray/usr/share/doc/nekoray/copyright <<-EOF
Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
Upstream-Name: nekoray
Source: https://github.com/AL4AL/nekoray

Files: *
Copyright: 2020-2024 MatsuriDayo
           2026 AL4AL
License: GPL-3.0+
 Comment: Qt based cross-platform GUI proxy configuration manager,
  derived from Qv2ray. Full license text: https://www.gnu.org/licenses/gpl-3.0.html
 .
EOF

cat >nekoray/usr/share/doc/nekoray/changelog <<EOF
nekoray ($version) stable; urgency=medium

  * Modern Ubuntu 24.04 / Debian 12 packaging: package-owned desktop entry
    and hicolor icons, /usr/bin/nekoray launcher, root-owned files,
    zstd compression, maintainer scripts with shebangs, data migration
    from older installs.

 -- AL4AL <kalantar98@gmail.com>  $(date -R)
EOF
gzip -9n nekoray/usr/share/doc/nekoray/changelog

# manual page for the launcher
mkdir -p nekoray/usr/share/man/man1
cat >nekoray/usr/share/man/man1/nekoray.1 <<EOF
.TH NEKORAY 1 "October 2026" "nekoray $version" "User Commands"
.SH NAME
nekoray \\- Qt based proxy configuration manager (sing-box backend)
.SH SYNOPSIS
.B nekoray
.RI [ options ]
.SH DESCRIPTION
NekoBox (NekoRay) is a Qt based GUI client to manage proxy configurations
with sing-box as its core. The Debian package launcher always appends
.B \\-appdata
so user data stays in
.I ~/.config/nekoray
even when the application itself lives in a root-owned
.IR /opt/nekoray .
.PP
Configuration left next to older (non \\-appdata) installations is copied
to
.I ~/.config/nekoray
on first start; the originals are kept.
.SH OPTIONS
.TP
.BI \\-appdata " [DIR]"
Use the shared config directory (or DIR) instead of the program directory.
.TP
.B \\-tray
Start minimized to the tray.
.TP
.B \\-debug
Enable debug logging.
.TP
.B \\-many
Ignore a running instance of the same config directory and start anyway.
.TP
.B \\-flag_reorder
Reorder configuration files and remove broken or orphaned entries.
.SH FILES
.TP
.I ~/.config/nekoray/config
Profiles, groups and routes (created on first start).
.SH SEE ALSO
Project page: https://github.com/AL4AL/nekoray
EOF
gzip -9n nekoray/usr/share/man/man1/nekoray.1

# lintian overrides: intentional design decisions
mkdir -p nekoray/usr/share/lintian/overrides
cat >nekoray/usr/share/lintian/overrides/nekoray <<'EOF'
# self-contained application install, allowed by Debian Policy 9.1.1
dir-or-file-in-opt
# sing-box core: intentionally a static single-file Go binary
statically-linked-binary
EOF

#### control ####

installed_size=$(du -sk nekoray | cut -f1)

cat >nekoray/DEBIAN/control <<-EOF
Package: nekoray
Version: $version
Section: net
Priority: optional
Architecture: $arch
Maintainer: AL4AL <kalantar98@gmail.com>
Installed-Size: $installed_size
Depends: libc6, libxcb-xinerama0, libqt5core5a, libqt5gui5, libqt5network5, libqt5widgets5, libqt5svg5, libqt5x11extras5, libcap2-bin, desktop-file-utils
Recommends: hicolor-icon-theme
Homepage: https://github.com/AL4AL/nekoray
Description: Qt based cross-platform GUI proxy configuration manager (sing-box)
 NekoBox (NekoRay) is a Qt based GUI client to manage proxy
 configurations, with sing-box as its core.
 .
 This package installs the application under /opt/nekoray, a /usr/bin/nekoray
 launcher that keeps all user data in ~/.config/nekoray (portable installs
 and data sitting next to the binary are imported there automatically on
 first run), plus a desktop entry with icons installed to the hicolor icon
 theme.
EOF

#### postinst ####

cat >nekoray/DEBIAN/postinst <<'EOF'
#!/bin/sh
set -e

case "$1" in
    configure)
        # TUN support for the core binary
        if command -v setcap >/dev/null 2>&1; then
            setcap cap_net_admin=ep /opt/nekoray/nekobox_core || true
        fi

        # refresh desktop-entry / icon-theme caches (hicolor-icon-theme and
        # desktop-file-utils ship dpkg triggers for these too, this just
        # makes it immediate on every setup)
        if command -v update-desktop-database >/dev/null 2>&1; then
            update-desktop-database -q /usr/share/applications || true
        fi
        if command -v gtk-update-icon-cache >/dev/null 2>&1 && [ -d /usr/share/icons/hicolor ]; then
            gtk-update-icon-cache -q -f -t /usr/share/icons/hicolor || true
        fi

        if [ -d /opt/nekoray/config/profiles ] && [ ! -d "$HOME/.config/nekoray/config/profiles" ]; then
            echo "nekoray: legacy data found in /opt/nekoray/config, it will be" \
                 "imported into ~/.config/nekoray on first start." >&2
        fi
        ;;
esac

exit 0
EOF

#### postrm ####

cat >nekoray/DEBIAN/postrm <<'EOF'
#!/bin/sh
set -e

case "$1" in
    remove|purge|upgrade|failed-upgrade|abort-install|abort-upgrade|deconfigure)
        if command -v update-desktop-database >/dev/null 2>&1; then
            update-desktop-database -q /usr/share/applications || true
        fi
        if command -v gtk-update-icon-cache >/dev/null 2>&1 && [ -d /usr/share/icons/hicolor ]; then
            gtk-update-icon-cache -q -f -t /usr/share/icons/hicolor || true
        fi
        ;;
esac

if [ "$1" = "purge" ]; then
    # /opt/nekoray is ours (Policy 9.1.1 allows removing the whole dir on
    # purge), but keep any config a non -appdata run may have written there
    if [ -d /opt/nekoray ]; then
        if [ -e /opt/nekoray/config ]; then
            backup="/var/backups/nekoray-config-$(date +%Y%m%d%H%M%S)"
            mkdir -p /var/backups
            mv /opt/nekoray/config "$backup"
            echo "nekoray: legacy config preserved in $backup" >&2
        fi
        rm -rf /opt/nekoray
    fi
fi

exit 0
EOF

chmod 0755 nekoray/DEBIAN/postinst nekoray/DEBIAN/postrm

# strip debug symbols from the GUI binary (the Go core is built with -s -w)
if command -v strip >/dev/null 2>&1; then
    strip --strip-unneeded nekoray/opt/nekoray/nekobox || true
fi

# Policy-friendly modes: no group/other write anywhere (dirs -> 755,
# data files -> 644, executables keep their +x)
chmod -R go-w nekoray

# dpkg md5sums (all payload files, DEBIAN/ itself excluded)
(
    cd nekoray
    find . -type f ! -path "./DEBIAN/*" -exec md5sum {} + | LC_ALL=C sort -k2 > DEBIAN/md5sums
)

#### build ####

# --root-owner-group: archive files are root:root even when built as a
# normal user (Ubuntu 24's dpkg supports it; no sudo needed)
dpkg-deb -Zzstd --root-owner-group --build nekoray "$deb_name.deb"

echo "built $deb_name.deb"
